### ISSUE TITLE
Issue running atw_vulkan.exe demo

### ISSUE THREAD

**Issue by lolomp2001** [KhronosGroup/Vulkan-Samples-Deprecated#51]
Hello,

Here is the output when I'm launching the demo :

```
Device Name          : AMD Radeon R9 200 Series
Device Type          : discrete GPU
Vendor ID            : XxXXXX
Device ID            : XxXXXX
Driver Version       : 1.2.0
API Version          : 1.0.17
Queue Families       : 0 = graphics compute transfer (1 queues, 2 priorities)
                       1 = compute transfer (2 queues, 2 priorities)
                       2 = transfer (2 queues, 2 priorities)
Required work queue family not supported.

No capable Vulkan physical device found.'atw_vulkan.exe' (Win32)
```

Sould I understand that my device is not compatible ?
If not, does it mean the code is developped for specific hardware ?

Thanks you.

**Comment by mre4ce** [comment]
To properly run this sample you indeed need a Vulkan driver that supports multiple graphics queues. You can run parts of the sample separately without the need for multiple queues.

"atw_vulkan.exe -r scene" will just render the scene.
"atw_vulkan.exe -r tw" will just render the time warp.

However, to render both the scene and the time warp you need a Vulkan graphics driver that supports multiple queues. To make this work with your graphics driver you can use the queue multiplexer layer which makes all Vulkan devices look like they have at least 16 queues per family. 

https://github.com/KhronosGroup/Vulkan-Samples/tree/master/samples/layers/queue_muxer

While this makes the sample work, this may noticeably reduce the performance.
