### ISSUE TITLE
apps/atw/* fail to build with recent GCC versions on Linux

### ISSUE THREAD

**Issue by TheRealCuran** [KhronosGroup/Vulkan-Samples-Deprecated#63]
I tried building the Vulkan-Samples with a recent GCC version (6.2.0 as shipped by Debian Stretch) but gut a failure for the binaries in apps/atw:

```
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_cpu_dsp.c: In function ‘Signal_Wait’:
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_cpu_dsp.c:6262:20: error: storage size of ‘ts’ isn’t known
    struct timespec ts;
                    ^~
```

The problem seems to be, that timespec is not defined with -std=c99. The patch at https://gist.github.com/TheRealCuran/08a3a62c8c03bebb38f4c0cd43120fad fixes this issue for me (sorry for the Gist mess, but apparently GitHub doesn't like patches).

**Comment by mre4ce** [comment]
Thanks for reporting this issue. Travis CI does not appear to report this problem, but I will give it a try with a couple of compilers.

**Comment by mre4ce** [comment]
Would you mind trying latest to see if that solves the problem for you? Thanks!

**Comment by TheRealCuran** [comment]
Nope, doesn't work (I did fresh clones of all three required repositories):

```
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_cpu_dsp.c: In function ‘Signal_Wait’:
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_cpu_dsp.c:6269:20: error: storage size of ‘ts’ isn’t known
    struct timespec ts;
                    ^~
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_cpu_dsp.c:6269:20: warning: unused variable ‘ts’ [-Wunused-variable]
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_opengl.c: In function ‘Signal_Wait’:
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_opengl.c:1134:20: error: storage size of ‘ts’ isn’t known
    struct timespec ts;
                    ^~
/tmp/test-vk/Vulkan-Samples/samples/apps/atw/atw_opengl.c:1134:20: warning: unused variable ‘ts’ [-Wunused-variable]
```

CMake said:

> cmake -DCMAKE_BUILD_TYPE=Release ../Vulkan-Samples
> -- The C compiler identification is GNU 6.2.0
> -- The CXX compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /tmp/test-vk/build

Applying my patch from the initial report still solves the problem.

**Comment by mre4ce** [comment]
Thanks for testing. Sorry I messed that up. In theory it should work now.

**Comment by TheRealCuran** [comment]
Yeah well, commit b74b36af60db167b75fca62c03ad7f913c78832f obviously works, that was after all the alternative given in the description of my patch. So yes, that fixes the issue for me. Thanks.

**Comment by mre4ce** [comment]
Thanks again for testing. Sorry I didn't just apply your patch. I wanted to fully understand the problem.
