### ISSUE TITLE
atw_vulkan: Invalid image blit offsets

### ISSUE THREAD

**Issue by daek-img** [KhronosGroup/Vulkan-Samples-Deprecated#80]
In samples/apps/atw/atw_vulkan.c, srcOffsets[1].z and dstOffsets[1].z are being set to 0 on vkCmdBlitImage(). However, according to the spec:

>If the calling command’s srcImage is of type VK_IMAGE_TYPE_1D or VK_IMAGE_TYPE_2D, then srcOffset[0].z must be 0 and srcOffset[1].z must be 1. 
>[...]
>If the calling command’s dstImage is of type VK_IMAGE_TYPE_1D or VK_IMAGE_TYPE_2D, then dstOffset[0].z must be 0 and dstOffset[1].z must be 1.

**Comment by daek-img** [comment]
Should be fixed in https://github.com/KhronosGroup/Vulkan-Samples/pull/84

**Comment by mre4ce** [comment]
Thanks for pointing this out. This should have been resolved a while back,
